### ISSUE TITLE
输入指令时没有反应

### ISSUE THREAD

**Issue by LambdaYH** [shine5402/mirai-KeywordReply#1]
![image](https://user-images.githubusercontent.com/13503375/90310893-67b7b500-df28-11ea-99f9-7ae1d558f185.png)
![image](https://user-images.githubusercontent.com/13503375/90310966-ef052880-df28-11ea-92b1-ede31acad87e.png)
![image](https://user-images.githubusercontent.com/13503375/90310972-f75d6380-df28-11ea-816d-b9f7ea0dca13.png)
可否直接给出setting.yml格式

**Comment by LambdaYH** [comment]
误解了，原来是在console中输入

**Comment by shine5402** [comment]
请问您添加自己为机器人的manager了吗？虽然因为/ping被响应了看起来应该没问题……但还是在这里列举一下。
你需要先在console中指定自己的账号为机器人的manager，这样子机器人才会在聊天中响应命令。
请在console中输入 /manager add 骰子的QQ号 你的QQ号 来添加自己为管理者

之后是关于settings.yml的格式 这里简单说一下。以下是一段示例：

```
rules:
- replies:
  - 测试1
  - 测试2
  - 测试3
  groups: []
  type: exact
  keyword: 测试
version: 2
```

settings.yml里，有一个rules数组用来放置规则，每个元素都是一条规则。每个元素中有四个成员，分别是replies，groups，type，keyword。replies是放置回复的字符串数组，groups是放置群号的数组，会被解析为长整形。type是用来标识类型的字符串，目前版本可能值为exact、vague、regex，分别对应各匹配模式，keyword是关键词字符串。和rules平级的version字段用来存储settings.yml的格式版本信息。

**Comment by LambdaYH** [comment]
好的谢谢，添加自己为manager后会在聊天窗口中响应命令了，/ping是HTTP插件的响应。
请问现在支持关键词回复内容为图片吗？

**Comment by shine5402** [comment]
因为我还没研究所以暂时不支持……不好意思……！！！这个倒是可以作为一个TODO，日后研究一下写进来

**Comment by LambdaYH** [comment]
辛苦作者大大😄
