### ISSUE TITLE
反馈一个问题

### ISSUE THREAD

**Issue by zht163** [shine5402/mirai-KeywordReply#2]
当添加中文关键词或回复词会boom
修改settings.yml文件(添加中文关键词)然后load也不行
![bug](https://user-images.githubusercontent.com/48507961/90388825-04aa5780-e0bb-11ea-980b-d3fa0b93d2e3.jpg)

**Comment by shine5402** [comment]
console侧大概是console对中文处理的问题 这个我没办法解决！可以设置自己的账号为manager（见issue #1 ）然后小窗/群聊输入命令
settings.yml 不行倒是比较微妙……确认自己是按照yaml的格式输入字符串了吗？还请确认一下！
最后，谢谢反馈！

**Comment by zht163** [comment]
帮我看一下修改配置文件然后reload的这个操作有没问题

**Comment by shine5402** [comment]
请提供您遇到问题的settings.yml的内容 我找个时间测试一下

**Comment by zht163** [comment]
测试了一下，群里manager模式添加中文问答是没问题的，配置文件在附件里

**Comment by shine5402** [comment]
Github好像没有把issue邮件里的附件附上 可以直接粘贴内容或者使用网盘分享（

**Comment by zht163** [comment]
rules:
- replies:
&nbsp; - 这
&nbsp; groups: []
&nbsp; type: vague
&nbsp; keyword: 啊
version: 2

**Comment by shine5402** [comment]
看来问题是load命令没有重新从硬盘重新读取的问题。之后会发新版本修复这个bug 感谢反馈！

**Comment by zht163** [comment]
好的

**Comment by zht163** [comment]
可以支持发送图片吗

**Comment by shine5402** [comment]
日后有可能 但目前比较忙 没去研究

**Comment by zht163** [comment]
好的
